import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import PreguntasProteccion3 from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasProteccion3.jsx";
import PreguntasRiesgosMecanicos from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasRiesgosMecanicos.jsx";
import PreguntasRiesgosTermicos from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasRiesgosTermicos.jsx";
// import DragAndDropManos from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/DragAndDropManos.jsx";
// import SelectAndValidateMobile from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/SelectAndValidateMobile.jsx";
import PreguntasSeleccionHerramientas from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasSeleccionHerramientas.jsx";
import OrdenarPasos from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/OrdenarPasos.jsx";
import OrdenarPasosPalmaManos from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/OrdenarPasosPalmaManos.jsx";
import OrdenarPasosMobile from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/OrdenarPasosMobile.jsx";
import Pregunta1alturas from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/Pregunta1alturas.jsx";
import Pregunta2alturas from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/Pregunta2alturas.jsx";
import SeleccionImagenesAlturas from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/SeleccionImagenesAlturas.jsx";
import DragAndDropAlturas1 from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropAlturas1.jsx";
import DragAndDropAlturas1Movil from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropAlturas1Movil.jsx";
import CardsInfoAlturas from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/CardsInfoAlturas.jsx";
import DragAndDrop from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/DragAndDrop.jsx";
import PreguntasTiposRiesgo from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasTiposRiesgo.jsx";
import PreguntasTiposRiesgoMobile from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasTiposRiesgoMobile.jsx";
import PreguntasVorF from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasVorF.jsx";
import ActividadListaDesplegable from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/ActividadListaDesplegable.jsx";
import PreguntasAlturas1 from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/PreguntasAlturas1.jsx";
import DragAndDropAlturas2 from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropAlturas2.jsx";
import DragAndDropAlturas2Movil from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropAlturas2Movil.jsx";
import ActividadFalsoVerdadero from "./pages/Actividades/Actividades_Espacios_Confinados/Actividad_Falso_Verdadero.jsx";
import Drag_And_Drop from "./pages/Actividades/Actividades_Espacios_Confinados/Drag_And_Drop.jsx";
// import Drag_And_DropMobile from "./pages/Actividades/Actividades_Espacios_Confinados/Drag_And_DropMobile.jsx";
import EPSLugaresConfinados from "./pages/Actividades/Actividades_Espacios_Confinados/EPS_Lugares_Confinados.jsx";
import ActividadMobileEntradaSalida from "./pages/Actividades/Actividades_Espacios_Confinados/Actividad_Mobile_Entrada_Salida.jsx";
// import Drag_And_Drop from "./pages/Actividades/Actividades_Espacios_confinados/Drag_And_Drop.jsx";
import OrdenarPasosPalmaManosMobile from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/OrdenarPasosPalmaManosMobile.jsx";
import PreguntasSiNo from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasSiNo.jsx";
import EspaciosConfinadosSeleccionMultiple from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/EspaciosConfinadosSeleccionMultiple.jsx";
import SeleccionEspaciosConfinados from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/SeleccionEspaciosConfinados.jsx";
import "./main.css";
import Slider13_Lista_desplegable from "./pages/Actividades/Actividades_Espacios_Confinados/Slider13_Lista_desplegable.jsx";
import Slider13_Lista_desplegable_movil from "./pages/Actividades/Actividades_Espacios_Confinados/Slider13_Lista_desplegable_movil.jsx";
import DragAndDropAudios from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropAudios.jsx";
import DragAndDropAudiosMovil from "./pages/Actividades/Actividades_Espacios_Confinados/DragAndDropAudiosMovil.jsx";
import Palabra_CorrectaMovil from "./pages/Actividades/Actividades_Espacios_Confinados/Slider13_Lista_desplegable_movil.jsx";
import Slider12_drag_and_drop_audios_movil from "./pages/Actividades/Actividades_Espacios_Confinados/Slider12_drag_and_drop_audios_movil.jsx";
import Slider14_Lista_desplegable from "./pages/Actividades/Actividades_Espacios_Confinados/Slider14_Lista_desplegable.jsx";
import Slider14_Lista_desplegable_movil from "./pages/Actividades/Actividades_Espacios_Confinados/Slider14_Lista_desplegable_movil.jsx";
import Slider12_drag_and_drop_audios from "./pages/Actividades/Actividades_Espacios_Confinados/Slider12_drag_and_drop_audios.jsx";
import Slider15_Lista_desplegable from "./pages/Actividades/Actividades_Espacios_Confinados/Slider15_Lista_desplegable.jsx";
import Slider15_Lista_desplegable_movil from "./pages/Actividades/Actividades_Espacios_Confinados/Slider15_Lista_desplegable_movil.jsx";
import PreguntasRiesgosTermicosV2 from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/PreguntasRiesgosTermicosV2.jsx";
import Sliderppt24_SeleccionMultiple from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt24_SeleccionMultiple.jsx";
import Sliderppt9_DragAndDrop from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt9_DragAndDrop.jsx";
import Sliderppt15_SeleccionMultipleCheckbox from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt15_SeleccionMultipleCheckbox.jsx";
import Sliderppt16_SeleccionPreguntasParte1 from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt16_SeleccionPreguntasParte1.jsx";
import Sliderppt17_SeleccionPreguntasParte2 from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt17_SeleccionPreguntasParte2.jsx";
import Sliderppt26_PreguntasTF from "./pages/Actividades/Actividades_Uso_Seguro_Andamios/Sliderppt26_PreguntasTF.jsx";
import Sliderppt18_SeleccionPreguntas from "./pages/Actividades/Actividades_PESV/Sliderppt18_SeleccionPreguntas.jsx";
import Sliderppt19_SeleccionPreguntasAudios from "./pages/Actividades/Actividades_PESV/Sliderppt19_SeleccionPreguntasAudios.jsx";
import PreguntasFactorHumanoTF from "./pages/Actividades/Actividades_PESV/PreguntasFactorHumanoTF.jsx";
import PreguntasFactorHumano from "./pages/Actividades/Actividades_PESV/PreguntasFactorHumano.jsx";
import OrdenarElementos from "./pages/Actividades/Actividades_PESV/OrdenarElementos.jsx";
import PPT14_EscogerOpcionSirena from "./pages/Actividades/Actividades_PESV/PPT14_EscogerOpcionSirena.jsx";
import SlidePP11_seleccione from "./pages/Actividades/Actividades_PESV/SlidePP11_seleccione.jsx";
import Sliderppt8_seleccione from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt8_seleccione.jsx";
import Sliderppt13_seleccione_audio from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt13_seleccione_audio.jsx";
import Sliderppt15_dragandrop_audios from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt15_dragandrop_audios.jsx";
import Sliderppt16_seleccione_multiple from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt16_seleccione_multiple.jsx";
import Sliderppt18_seleccione_multiple from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt18_seleccione_multiple.jsx";
import Sliderppt25_preguntasTF from "./pages/Actividades/Actividades_Izaje_Cargas/Sliderppt25_preguntasTF.jsx";
import Slidermobile_select_audios from "./pages/Actividades/Actividades_Izaje_Cargas/Slidermobile_select_audios.jsx";
import PicadurasAnimalesPeligrosos from "./pages/Actividades/Actividades_Riesgo_Biologico/PicadurasAnimalesPeligrosos.jsx";
import Sliderppt15_SeleccionPreguntasAudios from "./pages/Actividades/Actividades_Riesgo_psicosocial/Sliderppt15_SeleccionPreguntasAudios.jsx";
import DragAndDrop_Sistema_Oxiacetileno from "./pages/Actividades/Actividades_Soldaduras/DragAndDrop_Sistema_Oxiacetileno.jsx";
import DragAndDrop_Sistema_OxiacetilenoMobile from "./pages/Actividades/Actividades_Soldaduras/DragAndDrop_Sistema_OxiacetilenoMobile.jsx";
import Seleccione_EPP_Soldadura from "./pages/Actividades/Actividades_Soldaduras/Seleccione_EPP_Soldadura.jsx";
import Seleccione_EPP_SoldaduraMobile from "./pages/Actividades/Actividades_Soldaduras/Seleccione_EPP_SoldaduraMobile.jsx";
import ChileDAD from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/ChileDAD.jsx";
import ChileSeleccione from "./pages/Actividades/Actividades_Morelco_Riesgos_Manos/ChileSeleccione.jsx";
import PreguntasSeleccioneSiNo from "./pages/Actividades/Actividades_Riesgo_psicosocial/PreguntasSeleccioneSiNo.jsx";
import Slider10SeleccioneMultiple from "./pages/Actividades/Actividades_Riesgo_psicosocial/Slider10SeleccioneMultiple.jsx";
import Slider11SeleccioneMultipleV2 from "./pages/Actividades/Actividades_Riesgo_psicosocial/Slider11SeleccioneMultipleV2.jsx";
import DragAndDropArisM from "./pages/Actividades/Actividades_Aris_Mining/DragAndDropArisM.jsx";
import IdentificarRiesgosBiologicos from "./pages/Actividades/Actividades_Riesgo_Biologico/IdentificarRiesgosBiologicos.jsx";
import OrdenarMedidasCorrectivas from "./pages/Actividades/Actividades_Riesgo_Biologico/OrdenarMedidasCorrectivas.jsx";
import DragAndDropSlide9 from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragnAndDropSlide9.jsx";
import DragAndDropSlide9Movil from "./pages/Actividades/Actividades_Trabajo_seguro_alturas/DragAndDropSlide9Movil.jsx";
import PPT8_List_Desplegable from "./pages/Actividades/Actividades_PESV/PPT8_List_Desplegable.jsx";
import PPT_10_Preguntas from "./pages/Actividades/Herramientas de poder/PPT_10_Preguntas.jsx";
import PPT_11_List_Desplegable from "./pages/Actividades/Herramientas de poder/PPT_11_Lista_Desplegable.jsx";
import PPT_19_Preguntas from "./pages/Actividades/Herramientas de poder/PPT_19_Preguntas.jsx";
import PPT_21_DragAndDrop from "./pages/Actividades/Actividades_PESV/PPT_21_DragAndDrop.jsx";
import PPT_21_DragAndDrop_Mobile from "./pages/Actividades/Actividades_PESV/PPT_21_DragAndDrop_Mobile.jsx";
import PPT_22_Preguntas from "./pages/Actividades/Herramientas de poder/PPT_22_Preguntas.jsx";
import PPT_09_DragAndDrop from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_09_DragAndDrop.jsx";
import PPT_09_DragAndDrop_Mobile from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_09_DragAndDrop_Mobile.jsx";
import PPT_17_SeleccionMultiple from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_17_SeleccionMultiple.jsx";
import PPT_21_Preguntas from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_21_Preguntas.jsx";
import PPT_27_Lista_desplegable_imagen from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_27_Lista_desplegable_imagen.jsx";
import PPT_11_ListaDesplegable_Audios from "./pages/Actividades/Actividades_Izajes_De_Cargas/PPT_11_ListaDesplegable_Audios.jsx";
import DnD_Conceptos_Clave from "./pages/Actividades/Actividades_Tecnitanques_Soldadura/DnD_Conceptos_Clave.jsx";
import Conceptos_Clave_Selects from "./pages/Actividades/Actividades_Tecnitanques_Soldadura/Conceptos_Clave_Selects.jsx";
import IdentificaRolSoldadura from "./pages/Actividades/Actividades_Tecnitanques_Soldadura/IdentificaRolSoldadura.jsx";
import ActividadApoyoSocial from "./pages/Actividades/Actividades_Riesgo_Psicosocial/ActividadApoyoSocial.jsx"

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <DragAndDropAlturas2 />
  </React.StrictMode>
);
